# Generated by Django 2.1 on 2021-05-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
